# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestGit():
    def setup_method(self):
        self.vars = {}

        self.driver = webdriver.Chrome()
        self.driver.get("https://mathelilla.github.io/selenium_course/")
        self.driver.set_window_size(1226, 731)

    def teardown_method(self):
        self.driver.quit()

    def test_html(self):

        self.header_text = self.driver.find_element(By.XPATH, "//h1").text
        assert self.header_text == 'Calculator'

        self.first_input_element = self.driver.find_element(By.NAME, "a").send_keys(10)
        self.second_input_element = self.driver.find_element(By.NAME, "b").send_keys(20)

        self.submit_button = self.driver.find_element(By.ID, "submit-button").click()

        self.result = self.driver.find_element(By.NAME, "result").get_attribute("value")
        assert self.result == str(30)

        self.driver.save_screenshot("result2.png")
