# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

def test_course():
    driver = webdriver.Chrome()
    driver.get("https://mathelilla.github.io/selenium_course/")
    driver.set_window_size(1226, 731)
    driver.find_element(By.NAME, "a").send_keys("a")
    driver.find_element(By.NAME, "b").send_keys("b")
    driver.find_element(By., ".btn-primary").click()
        #assert self.driver.find_element(By.CSS_SELECTOR, ".alert").text == "Location has saved"

