# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestGit():
    def setup_method(self):
        self.vars = {}

        self.driver = webdriver.Chrome()
        self.driver.get("https://mathelilla.github.io/selenium_course/")
        self.driver.set_window_size(1226, 731)

    def teardown_method(self):
        self.driver.quit()

    def test_html(self):

        self.header_text = self.driver.find_element(By.XPATH, "//h1").text
        assert self.header_text == 'Calculator'

        first_number = input("Give the first number! ")
        second_number = input("Give the second number! ")

        self.first_input_element = self.driver.find_element(By.NAME, "a").send_keys(first_number)
        self.second_input_element = self.driver.find_element(By.NAME, "b").send_keys(second_number)

        self.submit_button = self.driver.find_element(By.ID, "submit-button").click()

        self.result = self.driver.find_element(By.NAME, "result").get_attribute("value")
        assert self.result == str(int(first_number) + int(second_number))

        self.driver.save_screenshot("result.png")

f = TestGit()
f.setup_method()
f.test_html()
f.teardown_method()